### PR TITLE
Creating GetProjectsInTeam method and sample project

### PR DESCRIPTION
**Pull request by fabionaspolini**
Creating method to get all projects linked to the team.
Adding project with example of use of the framework.
Fixing XML file path bug in template AsanaFunctions.tt

### CODE REVIEW

**Comment by acron0** [comment]
Thanks for your contribution. Can you add a brief description?

**Comment by fabionaspolini** [comment]
Creating method to get all projects linked to the team.
Adding project with example of use of the framework.
Fixing XML file path bug in template AsanaFunctions.tt

**Comment by fabionaspolini** [comment]
@acron0 is everything correct to merge my commits to master? I am going to start making new improvements and plan to continue in this repository with my evolutions.

**Comment by acron0** [comment]
Thank you @fabionaspolini

**Pull request merged**
